AllCops:
  Exclude:
    - 'spec/lib/compiler/generate_factory_spec.rb'
    - 'spec/factories/default/core/delete_spec.rb'
    - 'spec/factories/default/core/deny_spec.rb'
    - 'spec/factories/default/core/grant_spec.rb'
    - 'spec/factories/default/core/group_spec.rb'
    - 'spec/factories/default/core/host_spec.rb'
    - 'spec/factories/default/core/layer_spec.rb'
    - 'spec/factories/default/core/permit_spec.rb'
    - 'spec/factories/default/core/policy_spec.rb'
    - 'spec/factories/default/core/revoke_spec.rb'
    - 'spec/factories/default/core/user_spec.rb'
    - 'spec/factories/default/core/variable_spec.rb'
    - 'spec/factories/default/core/webservice_spec.rb'
    - 'spec/factories/default/connections/database_spec.rb'
    - 'spec/factories/default/authenticators/authn_azure_spec.rb'
    - 'spec/factories/default/authenticators/authn_gcp_spec.rb'
    - 'spec/factories/default/authenticators/authn_iam_spec.rb'
    - 'spec/factories/default/authenticators/authn_jwt_jwks_spec.rb'
    - 'spec/factories/default/authenticators/authn_jwt_public_key_spec.rb'
    - 'spec/factories/default/authenticators/authn_oidc_spec.rb'
